document.addEventListener('DOMContentLoaded', () => {
  const detail = location.pathname.replaceAll('\\','/').includes('/services/');
  const base = detail ? '../' : '';
  const header = document.querySelector('header');

  // One source of truth for navigation: detail pages are upgraded to the same floating header at runtime.
  if (header) {
    header.className = 'fixed top-0 left-0 right-0 z-50 px-3 md:px-6';
    header.innerHTML = `<div class="nav-shell max-w-7xl mx-auto mt-3 rounded-2xl bg-navy shadow-xl px-4 md:px-7 py-3"><nav class="flex items-center justify-between gap-4" aria-label="Main navigation"><div class="hidden lg:flex flex-1 items-center gap-5"><a class="text-white/80 text-sm line-link" href="${base}index.html">Home</a><a class="text-white/80 text-sm line-link" href="${base}services.html">Services</a><a class="text-white/80 text-sm line-link" href="${base}car-care.html">Car Care</a></div><a href="${base}index.html" class="shrink-0" aria-label="US Autos and Tires home"><img class="logo-img" src="${base}assets/images/logo.png" alt="US Auto Repair logo"></a><div class="hidden lg:flex flex-1 items-center justify-end gap-5"><a class="text-white/80 text-sm line-link" href="${base}about.html">About Us</a><a class="text-white/80 text-sm line-link" href="${base}gallery.html">Gallery</a><a class="text-white/80 text-sm line-link" href="${base}coupons.html">Coupons</a><a class="bg-red hover:bg-red2 text-white text-xs font-semibold rounded-full px-4 py-3 transition" href="tel:17542235452">Call (754) 223-5452</a></div><button data-menu aria-expanded="false" class="lg:hidden text-white text-2xl p-2" aria-label="Open menu"><span>☰</span></button></nav><div data-panel class="hidden lg:hidden border-t border-white/10 mt-3 pt-3 pb-2"><div class="grid gap-1"><a class="text-white py-3" href="${base}index.html">Home</a><a class="text-white py-3" href="${base}services.html">Services</a><a class="text-white py-3" href="${base}car-care.html">Car Care</a><a class="text-white py-3" href="${base}about.html">About Us</a><a class="text-white py-3" href="${base}gallery.html">Gallery</a><a class="text-white py-3" href="${base}coupons.html">Coupons</a><a class="bg-red text-white text-center rounded-full px-4 py-3 mt-2" href="tel:17542235452">Call (754) 223-5452</a></div></div></div>`;
  }

  const footer = document.querySelector('footer');
  if (footer) {
    footer.className = 'site-footer bg-navy text-white py-16 pb-24 md:pb-16';
    footer.innerHTML = `<div class="max-w-7xl mx-auto px-6 grid md:grid-cols-3 gap-12"><div><img class="logo-img" src="${base}assets/images/logo.png" alt="US Auto Repair logo"><p class="text-white/60 leading-7 mt-5">Dealership-level precision for European and luxury vehicles, at independent-shop pricing.</p></div><div><h2 class="font-poppins text-lg">Quick links</h2><div class="grid grid-cols-2 gap-3 mt-5 text-white/60 text-sm"><a class="line-link" href="${base}index.html">Home</a><a class="line-link" href="${base}services.html">Services</a><a class="line-link" href="${base}car-care.html">Car Care</a><a class="line-link" href="${base}about.html">About Us</a><a class="line-link" href="${base}gallery.html">Gallery</a><a class="line-link" href="${base}coupons.html">Coupons</a></div></div><div><h2 class="font-poppins text-lg">Service point</h2><p class="text-white/60 leading-7 mt-5">770 N State Rd 7<br>Plantation, FL 33317<br><a class="text-white line-link" href="tel:17542235452">(754) 223-5452</a></p><p class="font-mono text-xs text-white/40 mt-4">MON–FRI 8–6 · SAT 9–4 · SUN CLOSED</p></div></div><div class="max-w-7xl mx-auto px-6 mt-12 pt-6 border-t border-white/10 text-white/40 text-xs">© 2026 US Autos &amp; Tires. All rights reserved.</div>`;
  }

  const workOrder = document.querySelector('.work-order');
  if (workOrder) {
    const orders = [
      {vehicle:'BMW 3 Series', service:'Brake inspection', tech:'ASE certified', time:'45–60 min', status:'IN SERVICE'},
      {vehicle:'Mercedes-Benz C-Class', service:'Engine diagnostics', tech:'ASE certified', time:'30–45 min', status:'DIAGNOSING'},
      {vehicle:'Audi Q5', service:'Wheel alignment', tech:'ASE certified', time:'60–90 min', status:'IN SERVICE'},
      {vehicle:'Porsche Macan', service:'Fluid service', tech:'ASE certified', time:'45–75 min', status:'CHECKING IN'},
      {vehicle:'Land Rover Discovery', service:'Battery testing', tech:'ASE certified', time:'20–30 min', status:'IN SERVICE'},
      {vehicle:'Domestic / Asian make', service:'Oil & filter change', tech:'ASE certified', time:'30–45 min', status:'READY FOR REVIEW'}
    ];
    const order = orders[Math.floor(Math.random() * orders.length)];
    const orderNumber = String(480 + Math.floor(Math.random() * 40)).padStart(5, '0');
    const leaf = [...workOrder.querySelectorAll('*')].filter(el => el.children.length === 0);
    const orderTitle = leaf.find(el => /Work order/i.test(el.textContent));
    if (orderTitle) orderTitle.textContent = `Work order #${orderNumber}`;
    const field = label => { const node = [...workOrder.querySelectorAll('dl div')].find(el => el.querySelector('dt')?.textContent.toLowerCase().includes(label)); return node?.querySelector('dd'); };
    if (field('vehicle')) field('vehicle').textContent = order.vehicle;
    if (field('service')) field('service').textContent = order.service;
    if (field('technician')) field('technician').textContent = order.tech;
    if (field('est. time')) field('est. time').textContent = order.time;
    const status = workOrder.querySelector('.pulse-dot');
    if (status) status.innerHTML = `<i class="w-2 h-2 bg-ok rounded-full"></i> ${order.status}`;
    workOrder.classList.add('work-order-swap');
  }

  const shell = document.querySelector('.nav-shell');
  const menu = document.querySelector('[data-menu]');
  const panel = document.querySelector('[data-panel]');
  if (menu && panel) menu.addEventListener('click', () => { const open = !panel.classList.toggle('hidden'); menu.setAttribute('aria-expanded', open); menu.querySelector('span').textContent = open ? '×' : '☰'; });

  const onScroll = () => { shell?.classList.toggle('scrolled', scrollY > 16); document.querySelector('[data-top]')?.classList.toggle('hidden', scrollY < 600); document.querySelector('.mobile-call')?.classList.toggle('translate-y-full', scrollY < 280); };
  addEventListener('scroll', onScroll, { passive: true }); onScroll();
  document.querySelectorAll('a[href^="#"]').forEach(a => a.addEventListener('click', e => { const el = document.querySelector(a.getAttribute('href')); if (el) { e.preventDefault(); el.scrollIntoView({ behavior: 'smooth' }); } }));

  const pageName = location.pathname.replaceAll('\\','/').split('/').pop().replace('.html','') || 'index';
  const addSection = html => { const node = document.createElement('div'); node.innerHTML = html.trim(); const section = node.firstElementChild; document.querySelector('main')?.appendChild(section); return section; };

  // Three purpose-built interactions per main page, kept lightweight and native to the shop.
  const mainPageTools = {
    index: `<section class="page-tools py-20 md:py-28"><div class="max-w-7xl mx-auto px-6"><div class="eyebrow">SERVICE DESK / QUICK MATCH</div><h2 class="font-poppins text-4xl md:text-5xl mt-5">Three ways to get a clearer next step.</h2><div class="grid lg:grid-cols-3 gap-5 mt-10"><div class="tool-card"><span class="font-mono text-red text-xs">01 / SYMPTOM ROUTER</span><h3 class="font-poppins text-xl mt-4">What’s wrong with my car?</h3><select class="tool-select mt-5" data-match><option value="">Choose a symptom</option><option value="brake-inspections.html">Soft or noisy brakes</option><option value="engine-diagnostics.html">Warning light or rough running</option><option value="wheel-alignments.html">Pulling or uneven tire wear</option><option value="battery-testing.html">Slow start or no-start</option></select><p class="tool-result mt-4" data-match-result>Pick a symptom to route yourself to a service.</p></div><div class="tool-card"><span class="font-mono text-red text-xs">02 / RANGE CHECK</span><h3 class="font-poppins text-xl mt-4">Ballpark the conversation.</h3><div class="grid grid-cols-2 gap-2 mt-5"><select class="tool-select" data-cost-service><option value="">Service</option><option value="maintenance">Maintenance</option><option value="brakes">Brakes</option><option value="diagnostics">Diagnostics</option></select><select class="tool-select" data-cost-vehicle><option value="">Vehicle</option><option value="everyday">Domestic / Asian</option><option value="european">European / Luxury</option></select></div><p class="tool-result mt-4" data-cost-result>Choose both to see a planning range.</p><small class="font-mono text-[10px] text-steel">CONFIRMED FREE AFTER DIAGNOSIS · NOT A QUOTE</small></div><div class="tool-card"><span class="font-mono text-red text-xs">03 / FIND THE BAY</span><h3 class="font-poppins text-xl mt-4">Get directions to the shop.</h3><input class="tool-input mt-5" data-address placeholder="Starting address or ZIP" aria-label="Starting address or ZIP"><button class="tool-button mt-3" data-directions>Open driving directions ↗</button><p class="tool-result mt-4">770 N State Rd 7 · Plantation, FL 33317</p></div></div></div></section>`,
    services: `<section class="page-tools py-20 md:py-28 bg-paper-2"><div class="max-w-7xl mx-auto px-6"><div class="eyebrow">SERVICE DESK / SORT THE SIGNAL</div><h2 class="font-poppins text-4xl mt-5">Find the right lane faster.</h2><div class="flex flex-wrap gap-2 mt-8"><button class="tool-tab active" data-service-filter="all">All services</button><button class="tool-tab" data-service-filter="maintenance">Maintenance</button><button class="tool-tab" data-service-filter="repair">Repair</button><button class="tool-tab" data-service-filter="diagnostics">Diagnostics</button></div><div class="grid md:grid-cols-3 gap-5 mt-8" data-service-filter-grid><article class="tool-card" data-service-category="maintenance"><span class="font-mono text-red text-xs">MAINTENANCE</span><h3 class="font-poppins text-xl mt-3">Oil, tires, fluids</h3><p class="text-steel mt-2">Keep the everyday systems predictable.</p></article><article class="tool-card" data-service-category="repair"><span class="font-mono text-red text-xs">REPAIR</span><h3 class="font-poppins text-xl mt-3">Brakes, transmission, suspension</h3><p class="text-steel mt-2">Restore control, comfort and drivability.</p></article><article class="tool-card" data-service-category="diagnostics"><span class="font-mono text-red text-xs">DIAGNOSTICS</span><h3 class="font-poppins text-xl mt-3">Engine and battery testing</h3><p class="text-steel mt-2">Turn symptoms into useful information.</p></article></div><div class="quiz-box mt-8"><span class="font-mono text-red text-xs">MINI QUIZ</span><p class="font-poppins text-xl mt-3" data-quiz-question>Is the vehicle warning you, wearing unevenly, or struggling to move?</p><div class="flex flex-wrap gap-2 mt-4"><button class="tool-tab" data-quiz="warning">Warning light</button><button class="tool-tab" data-quiz="wear">Wear or handling</button><button class="tool-tab" data-quiz="move">Starting or shifting</button></div><p class="tool-result mt-4" data-quiz-result>Choose the closest description.</p></div></div></section>`,
    'car-care': `<section class="page-tools py-20 md:py-28"><div class="max-w-7xl mx-auto px-6 grid lg:grid-cols-2 gap-8"><div class="tool-card"><div class="eyebrow">MAINTENANCE CLOCK</div><h2 class="font-poppins text-3xl mt-4">Tell us the mileage.</h2><input class="tool-input mt-5" type="number" min="0" placeholder="Current mileage" data-mileage><p class="tool-result mt-4" data-mileage-result>We’ll highlight a useful starting point.</p><div class="mileage-track mt-5"><span data-mileage-marker></span></div></div><div class="tool-card"><div class="eyebrow">DASHBOARD TRANSLATOR</div><h2 class="font-poppins text-3xl mt-4">Tap a warning-light family.</h2><div class="warning-grid mt-5"><button data-warning="engine">◉<span>Engine</span></button><button data-warning="brake">◌<span>Brake</span></button><button data-warning="battery">▣<span>Battery</span></button><button data-warning="tire">◍<span>Tire</span></button></div><p class="tool-result mt-5" data-warning-result>Select a light to get a plain-language cue.</p></div></div></section>`,
    about: `<section class="page-tools py-20 md:py-28 bg-paper-2"><div class="max-w-7xl mx-auto px-6"><div class="eyebrow">SHOP STANDARD / WHY IT MATTERS</div><h2 class="font-poppins text-4xl mt-5">The details behind the promise.</h2><div class="grid md:grid-cols-3 gap-5 mt-10"><article class="cert-card tool-card"><div class="cert-seal">ASE</div><h3 class="font-poppins text-xl mt-5">ASE certified</h3><p class="cert-more text-steel mt-3">ASE certification is a recognized testing and credential standard for automotive technicians. It signals training and a commitment to measured work.</p></article><article class="facility-card tool-card"><div class="font-mono text-red text-xs">FACILITY / 01</div><h3 class="font-poppins text-xl mt-5">Modern diagnostic equipment</h3><p class="text-steel mt-3">Information first means the repair conversation starts with evidence.</p></article><article class="facility-card tool-card"><div class="font-mono text-red text-xs">FACILITY / 02</div><h3 class="font-poppins text-xl mt-5">Plain-language work orders</h3><p class="text-steel mt-3">You see the cost and next step before work starts.</p></article></div></div></section>`,
    gallery: `<section class="page-tools py-20 md:py-28 bg-paper-2"><div class="max-w-7xl mx-auto px-6"><div class="eyebrow">SHOP VIEW / COMPARE THE DETAIL</div><h2 class="font-poppins text-4xl mt-5">Before and after, side by side.</h2><div class="compare-box mt-10"><img src="assets/images/live-service.jpg" alt="Service bay detail from the reference shop gallery"><div class="compare-after"><img src="assets/images/live-brakes.jpg" alt="Brake detail from the reference shop gallery"></div><input type="range" min="10" max="90" value="52" data-compare aria-label="Before and after comparison"></div><p class="font-mono text-xs text-steel mt-4">DRAG THE DIVIDER · REFERENCE-SITE PHOTOGRAPHY</p></div></section>`,
    coupons: `<section class="page-tools py-20 md:py-28"><div class="max-w-7xl mx-auto px-6"><div class="eyebrow">OFFERS / READY WHEN VERIFIED</div><h2 class="font-poppins text-4xl mt-5">Keep the offer system useful.</h2><div class="flex flex-wrap gap-2 mt-8"><button class="tool-tab active" data-coupon-filter="all">All</button><button class="tool-tab" data-coupon-filter="maintenance">Maintenance</button><button class="tool-tab" data-coupon-filter="repair">Repair</button><button class="tool-tab" data-coupon-filter="seasonal">Seasonal</button></div><div class="grid md:grid-cols-3 gap-5 mt-8"><article class="tool-card coupon-tool" data-coupon-category="maintenance"><span class="font-mono text-red text-xs">MAINTENANCE</span><h3 class="font-poppins text-xl mt-3">Offer slot ready</h3><p class="text-steel mt-2">No current public offer was found on the reference site.</p><button class="tool-button mt-5" data-copy="CONFIRM-MAINTENANCE">Copy call note</button></article><article class="tool-card coupon-tool" data-coupon-category="repair"><span class="font-mono text-red text-xs">REPAIR</span><h3 class="font-poppins text-xl mt-3">Offer slot ready</h3><p class="text-steel mt-2">Call the shop to confirm any current repair promotion.</p><button class="tool-button mt-5" data-copy="CONFIRM-REPAIR">Copy call note</button></article><article class="tool-card coupon-tool" data-coupon-category="seasonal"><span class="font-mono text-red text-xs">SEASONAL</span><h3 class="font-poppins text-xl mt-3">Offer slot ready</h3><p class="text-steel mt-2">No invented discounts — this card stays ready for a verified offer.</p><button class="tool-button mt-5" data-copy="CONFIRM-SEASONAL">Copy call note</button></article></div><p class="font-mono text-xs text-steel mt-6">CURRENT STATUS: NO LIVE OFFERS PUBLISHED ON THE REFERENCE SITE AT RESEARCH TIME.</p></div></section>`
  };
  if (mainPageTools[pageName]) addSection(mainPageTools[pageName]);
  if (pageName === 'services') addSection(`<section class="py-16"><div class="max-w-7xl mx-auto px-6"><div class="eyebrow">MAKE-SPECIFIC LOOKUP</div><div class="tool-card mt-6 flex flex-col md:flex-row md:items-center justify-between gap-5"><div><h2 class="font-poppins text-2xl">What do you drive?</h2><p class="text-steel mt-2">Choose a make to surface the service conversations owners commonly start with.</p></div><select class="tool-select md:max-w-xs" data-make-lookup><option value="">Choose a make</option><option value="euro">BMW / Mercedes-Benz / Audi</option><option value="specialty">Porsche / Land Rover / Volvo</option><option value="all">Domestic or Asian make</option></select><p class="tool-result md:max-w-xs" data-make-result>Make-specific notes appear here.</p></div></div></section>`);
  if (pageName === 'car-care') addSection(`<section class="py-16 bg-paper-2"><div class="max-w-7xl mx-auto px-6"><div class="eyebrow">SOUTH FLORIDA CHECK</div><div class="tool-card mt-6 flex flex-col md:flex-row md:items-center justify-between gap-5"><div><h2 class="font-poppins text-2xl">Heat, rain or storm prep?</h2><p class="text-steel mt-2">Choose a season concern for a short checklist.</p></div><div class="flex flex-wrap gap-2"><button class="tool-tab" data-season="heat">Heat</button><button class="tool-tab" data-season="storm">Storm season</button><button class="tool-tab" data-season="rain">Heavy rain</button></div><p class="tool-result md:max-w-sm" data-season-result>Checklist appears here.</p></div></div></section>`);
  if (pageName === 'coupons') { const couponHero = [...document.querySelectorAll('main section')].find(section => section.textContent.includes('intentionally marked')); if (couponHero) { const heroCopy = couponHero.querySelector('p'); if (heroCopy) heroCopy.textContent = 'Current offers pulled from the live shop reference page. Confirm eligibility and terms before relying on any offer.'; } document.querySelectorAll('main section').forEach(section => { if (section.textContent.includes('No current public offer')) section.classList.add('hidden'); }); document.querySelectorAll('article').forEach(card => { if (card.textContent.includes('SAMPLE OFFER')) card.classList.add('hidden'); }); addSection(`<section class="py-20 md:py-28"><div class="max-w-7xl mx-auto px-6"><div class="eyebrow">REFERENCE SITE / CURRENT OFFERS</div><h2 class="font-poppins text-4xl mt-5">Offers currently listed by the shop.</h2><p class="text-steel mt-4 max-w-2xl">These offers were pulled from the live reference Coupons page. Confirm eligibility, terms and availability with the shop before relying on them.</p><div class="grid md:grid-cols-3 gap-5 mt-10"><article class="tool-card coupon-tool" data-coupon-category="maintenance"><span class="font-mono text-red text-xs">MAINTENANCE / LIVE LISTING</span><h3 class="font-poppins text-2xl mt-4">Up to $29.99</h3><p class="text-steel mt-2">Standard oil change.</p><p class="font-mono text-[10px] text-steel mt-6">COUPON REQUIRED · CONFIRM TERMS</p><button class="tool-button mt-5" data-copy="STANDARD-OIL-CHANGE">Copy call note</button></article><article class="tool-card coupon-tool" data-coupon-category="maintenance"><span class="font-mono text-red text-xs">MAINTENANCE / LIVE LISTING</span><h3 class="font-poppins text-2xl mt-4">Up to $15 off</h3><p class="text-steel mt-2">Full synthetic and semi-synthetic oil change.</p><p class="font-mono text-[10px] text-steel mt-6">COUPON REQUIRED · CONFIRM TERMS</p><button class="tool-button mt-5" data-copy="FULL-SYNTHETIC-OIL-CHANGE">Copy call note</button></article><article class="tool-card coupon-tool" data-coupon-category="repair"><span class="font-mono text-red text-xs">MAJOR REPAIR / LIVE LISTING</span><h3 class="font-poppins text-2xl mt-4">$0 towing</h3><p class="text-steel mt-2">Towing on all major repairs, as listed by the shop.</p><p class="font-mono text-[10px] text-steel mt-6">CONFIRM ELIGIBILITY BEFORE DISPATCH</p><button class="tool-button mt-5" data-copy="FREE-TOWING-MAJOR-REPAIR">Copy call note</button></article></div></div></section>`); }
  const localPhotos = ['live-service.jpg','live-brakes.jpg','live-engine.jpeg','live-oil.jpg','live-blue-car.jpg','live-parts.jpg','live-care.jpg','live-tow-truck.jpeg'];
  document.querySelectorAll('[data-gallery]').forEach((card, i) => { const photo = `${base}assets/images/${localPhotos[i % localPhotos.length]}`; card.setAttribute('src', photo); card.style.backgroundImage = `linear-gradient(0deg,#0f1b33d9,transparent 65%),url("${photo}")`; card.style.backgroundSize = 'cover'; card.style.backgroundPosition = 'center'; card.classList.add('photo-card'); });
  if (pageName === 'index') { const photoMap = [['ENGINE BAY / SAMPLE','live-engine.jpeg'],['TIRES & WHEELS / SAMPLE','live-blue-car.jpg'],['FACILITY / SAMPLE','live-service.jpg'],['TOW TRUCK / SAMPLE','live-tow-truck.jpeg']]; document.querySelectorAll('main section').forEach(section => photoMap.forEach(([label, photo]) => { const node = [...section.querySelectorAll('span')].find(s => s.textContent.includes(label)); if (node) { node.parentElement.style.backgroundImage = `linear-gradient(0deg,#0f1b33d9,transparent 65%),url("${base}assets/images/${photo}")`; node.parentElement.style.backgroundSize = 'cover'; node.parentElement.style.backgroundPosition = 'center'; } })); }

  const serviceDetails = {
    'oil-and-filter-changes': {code:'SVC-01',name:'Oil & Filter Changes',intro:'An oil service is more than draining a pan and twisting on a filter. The right oil grade, filter specification and service interval help an engine manage heat, friction and deposits through daily driving. We review the vehicle, its maintenance context and any visible concerns before recommending the next step.',includes:['Review the vehicle and current service history','Check oil level, condition and visible leaks','Confirm the correct oil and filter specification','Inspect the filter seal and drain area after service','Reset service information when appropriate','Record observations in a plain-language work order'],signs:['Oil warning light or low oil level','A new oil smell or visible spot under the vehicle','Mileage or time interval is due','No clear record of the last oil service'],euro:'European and luxury vehicles can use specific oil approvals, filter designs and electronic service intervals. Following the vehicle’s specification matters; a familiar-looking bottle or generic interval is not automatically the right answer.',process:['Listen to the concern and confirm the vehicle details','Inspect and explain what the current oil tells us','Present the service recommendation and cost','Complete the work, recheck and explain what changed'],faqs:[['How often should I change the oil?','Use the vehicle manufacturer’s guidance as a starting point, then account for heat, traffic and driving conditions. We can help interpret the interval for your vehicle.'],['Do you use the same oil for every car?','No. Oil grade and approval depend on the engine and vehicle requirements.'],['Is a warning light the same as an oil change reminder?','Not always. An oil-pressure warning needs attention and diagnosis rather than simply resetting a reminder.']]},
    'tire-rotations': {code:'SVC-02',name:'Tire Rotations',intro:'Tire rotation is a small service with a useful inspection built into it. Moving tires through the correct pattern can help even out wear, while the technician gets a close look at tread depth, pressure, sidewalls and the story the tires are telling about alignment or suspension.',includes:['Measure tread depth and compare positions','Inspect tread blocks for cupping or feathering','Check pressure and visible sidewall condition','Rotate according to the vehicle’s tire setup','Note directional, staggered or specialty-fit limitations','Explain whether alignment or tire replacement deserves a closer look'],signs:['Uneven wear across the axle or tread','Steering vibration or new road noise','Rotation interval is due','A vehicle pulls or feels less settled'],euro:'European and luxury vehicles often use staggered fitments, directional tires or performance compounds. The correct rotation pattern may be limited, so the inspection matters as much as the tire movement.',process:['Confirm tire size, fitment and the driver’s concern','Inspect wear, pressure and wheel condition','Choose the correct rotation or explain why it is limited','Road-check the result when appropriate and document the next look'],faqs:[['Can every tire be rotated?','No. Directional, staggered and some specialty tire setups have specific limitations.'],['Will rotation fix a vibration?','It may change a tire-related symptom, but vibration can also come from balance, alignment, suspension or wheel damage.'],['How do I know if wear is abnormal?','Compare the inner, center and outer tread, not just the visible outside shoulder.']]},
    'wheel-alignments': {code:'SVC-03',name:'Wheel Alignments',intro:'An alignment sets the relationship between the wheels, steering and road. It is not just about making a steering wheel look straight; it is about helping the vehicle track predictably and letting the tires meet the road as intended. We start with symptoms and tire wear, then measure before suggesting correction.',includes:['Review pulling, steering and road-feel symptoms','Inspect tire wear, pressure and visible suspension concerns','Measure alignment angles with appropriate equipment','Check steering-wheel center and tracking','Look for signs that a worn part may prevent a lasting correction','Explain the measured result and recommended next step'],signs:['Vehicle pulls left or right','Steering wheel sits off-center','Inner or outer tire edges wear quickly','The vehicle feels unsettled after a pothole or curb impact'],euro:'European and luxury vehicles can have tighter handling expectations and more complex suspension geometry. Correct angles matter for tire life, ride quality and the way advanced systems interpret steering input.',process:['Drive or discuss the symptom and conditions','Inspect tires, wheels and suspension interfaces','Measure the vehicle before adjusting anything','Correct what is serviceable and explain anything that needs repair first'],faqs:[['Do I need an alignment after new tires?','Not automatically, but checking wear and tracking can protect the investment in the tires.'],['Can an alignment fix a worn suspension part?','No. A worn component may need attention before an alignment can hold.'],['What if the car only pulls on crowned roads?','Road slope can affect feel; we compare the symptom across conditions rather than guessing.']]},
    'brake-inspections': {code:'SVC-04',name:'Brake Inspections',intro:'A brake inspection looks at more than pad thickness. Stopping feel, rotor condition, fluid, caliper movement, hardware and the vehicle’s use all contribute to a useful recommendation. We measure what we can see, listen to the concern and separate routine wear from a repair that actually needs attention.',includes:['Review pedal feel, noise, vibration and stopping behavior','Inspect pad thickness and wear balance','Check rotor surfaces and visible heat patterns','Review brake fluid condition and level','Inspect calipers, hoses and hardware where visible','Road-test when appropriate and explain urgency clearly'],signs:['Squealing, grinding or clicking while braking','A soft, low or changing pedal','Vibration through the pedal or steering wheel','The vehicle pulls or takes longer to settle'],euro:'European and luxury vehicles may use performance-oriented brake hardware, electronic parking brakes and specific service procedures. Correct parts and reset procedures matter to feel and function.',process:['Document what the driver notices and when it happens','Inspect the complete visible stopping system','Test or measure the relevant components','Present options by priority, not pressure'],faqs:[['How much pad thickness is safe?','Thickness is only one part of the decision; wear balance, rotor condition and usage matter too.'],['Do brake noises always mean the brakes are bad?','No. Noise can come from dust, material, hardware or wear, so it should be inspected.'],['Can I drive with a brake warning light?','A warning light deserves prompt attention. Call before continuing if braking feels different.']]},
    'battery-testing': {code:'SVC-05',name:'Battery Testing',intro:'A slow start or no-start can come from the battery, connections, starter, charging system or a draw while the vehicle is parked. Testing gives the conversation a starting point instead of turning the first guess into a parts list. We look at the starting system as a system.',includes:['Review the starting symptom and when it occurs','Inspect accessible battery case and terminals','Test battery condition and starting performance','Check charging-system behavior where appropriate','Look for obvious connection or corrosion concerns','Explain whether replacement, charging or more testing makes sense'],signs:['Slow cranking or repeated jump starts','Battery warning light','Electrical accessories behaving inconsistently','The vehicle sat unused or experienced severe heat'],euro:'European and luxury vehicles may package batteries in unusual locations and rely on battery-management systems. Replacement can require the correct battery type and registration procedure.',process:['Capture the exact no-start or slow-start pattern','Test before recommending a replacement','Check related starting and charging clues','Explain the next step and what the test does not prove'],faqs:[['Does a battery test check the alternator?','It can point toward charging concerns, but the charging system needs its own checks.'],['Why did the new battery go flat?','A weak battery, charging issue or parked electrical draw can each play a role.'],['Does heat affect batteries?','Heat can shorten battery life and make a marginal battery less predictable.']]},
    'fluid-services': {code:'SVC-06',name:'Fluid Services',intro:'Fluids carry heat, lubricate moving parts, transfer hydraulic force and protect systems from wear. A fluid service should match the vehicle, its specification and its condition — not simply a universal flush schedule. We inspect first and explain what the fluid is doing in the system.',includes:['Check fluid levels and visible condition','Look for leaks around accessible reservoirs and lines','Confirm vehicle-specific fluid requirements','Review service history and maintenance intervals','Inspect related filters or service points when applicable','Document what was checked and what should happen next'],signs:['Low fluid level or visible leak','Dark, contaminated or unusual-smelling fluid','Hard shifting or changing brake feel','A service interval is due without a clear record'],euro:'European vehicles often call for exact fluid specifications and procedures. Using the correct fluid protects seals, valves, clutches and electronic systems that may be less forgiving of substitutions.',process:['Identify the system and vehicle specification','Inspect condition and surrounding components','Explain whether a check, top-off or service is appropriate','Recheck levels and document the recommendation'],faqs:[['Should every fluid be flushed on a fixed schedule?','Not necessarily. The vehicle, fluid type, condition and use all matter.'],['Can low fluid cause a warning light?','It can, but a warning may also signal a leak, sensor or system fault.'],['Do you check for leaks during fluid service?','Visible leak checks are part of the inspection, with further testing if needed.']]},
    'engine-diagnostics': {code:'SVC-07',name:'Engine Diagnostics',intro:'A diagnostic scan is a starting point, not a verdict. Modern vehicles store clues across engine, emissions, fuel, ignition and networked systems. We pair the code or warning light with symptoms, inspection and testing so the recommendation speaks to the cause rather than simply naming a part.',includes:['Record warning lights and driving conditions','Scan relevant vehicle systems','Review stored, pending and history information','Inspect related wiring, connections and visible components','Test the system where the code points','Explain findings, limits and repair priorities'],signs:['Check-engine or emissions warning','Rough idle, hesitation or loss of power','Poor starting, stalling or unusual smell','A warning that returns after being cleared'],euro:'European and luxury vehicles can have more sensors, modules and manufacturer-specific procedures. Correct scan coverage and a disciplined test plan help avoid replacing expensive parts based on a single code.',process:['Listen to the symptom before scanning','Interpret data in the vehicle’s context','Test the most likely causes and verify the result','Present a work order in plain language'],faqs:[['Can you diagnose a warning light for free?','The shop’s promise is diagnosis is always free; the exact testing path is explained before work.'],['Does clearing the code fix the issue?','No. Clearing a code removes information without correcting the cause.'],['Why can two codes point to one problem?','Systems share information, so one fault can create several related messages.']]},
    'transmission-repairs': {code:'SVC-08',name:'Transmission Repairs',intro:'Transmission concerns often show up as a shift, hesitation, flare, noise, leak or change in engagement. Because several systems influence drivability, a useful repair process starts with the symptom and condition before anyone jumps to a rebuild or replacement. The aim is a measured path to the right decision.',includes:['Review shift timing, temperature and driving conditions','Inspect accessible fluid condition and leak areas','Scan transmission and related control systems','Check mounts, linkage and visible driveline concerns','Road-test when appropriate and safe','Explain repair, service or further-test options'],signs:['Delayed engagement or harsh shifts','Slipping, flaring or shuddering','Fluid leak or burning smell','A warning light connected to shifting or drivability'],euro:'European and luxury transmissions may use specific fluids, adaptations, mechatronics and software procedures. Correct diagnosis helps protect a complex and expensive system from guesswork.',process:['Document exactly when the shift concern happens','Inspect, scan and road-test where appropriate','Separate fluid, control, mechanical and related causes','Give the work order in priority order with clear choices'],faqs:[['Does dark fluid always mean the transmission is finished?','Fluid condition is a clue, not a complete diagnosis.'],['Can a transmission problem be electrical?','Yes. Controls, sensors, wiring and software can affect shifting.'],['Should I keep driving if it is slipping?','Call for guidance; continued use can change the condition and repair options.']]},
    'suspension-and-exhaust': {code:'SVC-09',name:'Suspension & Exhaust Repairs',intro:'Ride, handling, noise and exhaust concerns can overlap. A clunk may come from a mount, link, bushing or heat shield; a harsh ride may involve a spring, damper, tire or alignment. We trace the symptom to its source and explain how it affects safety, comfort, control and emissions.',includes:['Review noise, ride and handling conditions','Inspect accessible springs, dampers, links and bushings','Check exhaust pipes, shields, hangers and visible leaks','Look for tire or alignment clues that mimic suspension wear','Road-test when appropriate','Explain which concern is urgent, useful or monitorable'],signs:['Clunks over bumps or when turning','Vehicle bounces, leans or feels loose','Uneven tire wear or steering changes','Rattling, exhaust noise or fumes'],euro:'European and luxury vehicles often tune suspension for precise handling and may use complex links, electronic dampers or air systems. Correct parts and procedures protect the balance the vehicle was designed to have.',process:['Recreate the symptom and its conditions','Inspect the related suspension or exhaust area','Test and isolate the source rather than replacing by sound','Explain the repair path and any alignment follow-up'],faqs:[['Can a bad alignment cause suspension symptoms?','It can change tire wear and feel, but it does not explain every noise or loose component.'],['Is an exhaust rattle always a major repair?','Not always. A shield, hanger or mount can create noise, but it should be located.'],['Why does the car feel different after a pothole?','A tire, wheel, alignment or suspension component may have changed.']]}
  };
  if (detail && serviceDetails[pageName]) {
    const s = serviceDetails[pageName];
    addSection(`<section class="service-expansion py-20 md:py-28"><div class="max-w-5xl mx-auto px-6"><div class="eyebrow">${s.code} / FIELD GUIDE</div><h2 class="font-poppins text-4xl mt-5">A more useful look at ${s.name.toLowerCase()}.</h2><p class="text-steel leading-8 mt-6 max-w-3xl">${s.intro}</p><div class="grid lg:grid-cols-2 gap-12 mt-14"><div><div class="eyebrow">WHAT’S INCLUDED</div><ul class="detail-list mt-6">${s.includes.map(x=>`<li>✓ ${x}</li>`).join('')}</ul></div><div><div class="eyebrow">SIGNS TO PAY ATTENTION TO</div><ul class="detail-list mt-6">${s.signs.map(x=>`<li>→ ${x}</li>`).join('')}</ul></div></div><div class="grid lg:grid-cols-2 gap-12 mt-16"><div class="detail-panel"><div class="eyebrow">EUROPEAN &amp; LUXURY NOTE</div><p class="text-steel leading-8 mt-5">${s.euro}</p></div><div><div class="eyebrow">OUR PROCESS</div><ol class="process-list mt-5">${s.process.map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><p>${x}</p></li>`).join('')}</ol></div></div><div class="mt-16"><div class="eyebrow">SERVICE FAQ</div><div class="service-faq mt-6">${s.faqs.map((x,i)=>`<div class="faq-item"><button class="faq-question" aria-expanded="false">${x[0]}<span class="faq-chevron">⌄</span></button><p class="faq-answer">${x[1]}</p></div>`).join('')}</div></div></div></section>`);
  }

  // Purposeful automotive interaction: a small diagnostic console on every page.
  const main = document.querySelector('main');
  if (main && !main.querySelector('[data-car-console]')) {
    const title = detail ? 'Before the work order' : 'Your vehicle is giving you data';
    const consoleBlock = document.createElement('section');
    consoleBlock.className = 'site-enhancements py-20 md:py-28 bg-paper-2';
    consoleBlock.setAttribute('data-car-console', '');
    consoleBlock.innerHTML = `<div class="max-w-7xl mx-auto px-6 grid lg:grid-cols-[.9fr_1.1fr] gap-10 items-center"><div class="reveal"><div class="eyebrow">INTERACTIVE SERVICE CHECK</div><h2 class="font-poppins text-4xl md:text-5xl mt-5">${title}.</h2><p class="text-steel leading-7 mt-5">Choose the symptom that sounds familiar. We’ll show the kind of first look a technician may take — no scare tactics, just a clearer next step.</p><div class="flex flex-wrap gap-2 mt-7"><button class="console-choice active" data-symptom="light">Warning light</button><button class="console-choice" data-symptom="wear">Tire wear</button><button class="console-choice" data-symptom="noise">Strange noise</button></div><div class="console-output mt-6" aria-live="polite"><span class="font-mono text-red text-xs">READOUT / 01</span><p class="font-poppins text-xl mt-3">Start with the dashboard light and the conditions around it.</p><p class="text-steel text-sm mt-2">Diagnosis is always free. You approve the work before repairs begin.</p></div></div><div class="console-visual reveal delay-2"><div class="vehicle-orbit"><div class="scanline"></div><div class="orbit-car"><div class="car-roof"></div><div class="car-body"><span class="car-window"></span><span class="car-window second"></span></div><i class="wheel one"></i><i class="wheel two"></i></div><div class="orbit-ring ring-one"></div><div class="orbit-ring ring-two"></div></div><div class="font-mono text-xs text-steel text-center mt-4">LIVE BAY STATUS · READY FOR A CLEAR READ</div></div></div>`;
    main.appendChild(consoleBlock);
    const readouts = { light: ['READOUT / 01', 'Start with the dashboard light and the conditions around it.', 'A code is a clue. Testing and context help separate the signal from the source.'], wear: ['READOUT / 02', 'Check the tire pattern, pressure and alignment story.', 'Uneven wear can be useful information before a tire or suspension decision.'], noise: ['READOUT / 03', 'Locate when the sound happens: braking, turning, starting or cruising.', 'The timing and conditions help narrow the first inspection.'] };
    consoleBlock.querySelectorAll('[data-symptom]').forEach(button => button.addEventListener('click', () => { consoleBlock.querySelectorAll('.console-choice').forEach(b => b.classList.remove('active')); button.classList.add('active'); const r = readouts[button.dataset.symptom]; consoleBlock.querySelector('.console-output').innerHTML = `<span class="font-mono text-red text-xs">${r[0]}</span><p class="font-poppins text-xl mt-3">${r[1]}</p><p class="text-steel text-sm mt-2">${r[2]} Diagnosis is always free.</p>`; consoleBlock.querySelector('.vehicle-orbit').classList.remove('scan-active'); void consoleBlock.querySelector('.vehicle-orbit').offsetWidth; consoleBlock.querySelector('.vehicle-orbit').classList.add('scan-active'); }));
  }

  const io = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); io.unobserve(entry.target); } }), { threshold: .12 });
  document.querySelectorAll('.reveal').forEach(el => io.observe(el));
  document.querySelectorAll('[data-count]').forEach(el => { const obs = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { let n = 0; const end = +el.dataset.count; const step = Math.max(1, Math.ceil(end / 35)); const timer = setInterval(() => { n = Math.min(end, n + step); el.textContent = n + (el.dataset.suffix || ''); if (n >= end) clearInterval(timer); }, 35); obs.unobserve(entry.target); } })); obs.observe(el); });
  document.querySelectorAll('.faq-question').forEach(button => button.addEventListener('click', () => { const item = button.closest('.faq-item'); item.classList.toggle('open'); button.setAttribute('aria-expanded', item.classList.contains('open')); }));

  const lightbox = document.querySelector('[data-lightbox]'); let gallery = [], index = 0;
  document.querySelectorAll('[data-gallery]').forEach((image, i) => { gallery.push(image); image.addEventListener('click', () => { index = i; show(); }); });
  function show() { if (!lightbox || !gallery.length) return; lightbox.classList.remove('hidden'); lightbox.querySelector('img').src = gallery[index].src; lightbox.querySelector('img').alt = gallery[index].alt; }
  const close = () => lightbox?.classList.add('hidden'); document.querySelector('[data-close]')?.addEventListener('click', close); document.querySelector('[data-prev]')?.addEventListener('click', () => { index = (index + gallery.length - 1) % gallery.length; show(); }); document.querySelector('[data-next]')?.addEventListener('click', () => { index = (index + 1) % gallery.length; show(); });
  addEventListener('keydown', e => { if (e.key === 'Escape') close(); if (e.key === 'ArrowRight' && gallery.length) { index = (index + 1) % gallery.length; show(); } if (e.key === 'ArrowLeft' && gallery.length) { index = (index + gallery.length - 1) % gallery.length; show(); } });
  document.querySelectorAll('[data-filter]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-filter]').forEach(b => b.classList.remove('filter-active')); button.classList.add('filter-active'); const filter = button.dataset.filter; document.querySelectorAll('[data-gallery]').forEach(image => image.closest('[data-gallery-card]').classList.toggle('hidden', filter !== 'all' && image.dataset.category !== filter)); }));
  document.querySelector('[data-top]')?.addEventListener('click', () => scrollTo({ top: 0, behavior: 'smooth' }));

  document.querySelector('[data-match]')?.addEventListener('change', e => { const result = document.querySelector('[data-match-result]'); if (!e.target.value) return; result.innerHTML = `<a class="text-red font-semibold line-link" href="services/${e.target.value}">Open the recommended service page ↗</a>`; });
  const cost = { maintenance: '$89–$249', brakes: '$149–$699', diagnostics: '$0 diagnosis · repair scope follows testing' };
  const updateCost = () => { const service = document.querySelector('[data-cost-service]')?.value, vehicle = document.querySelector('[data-cost-vehicle]')?.value, result = document.querySelector('[data-cost-result]'); if (result && service && vehicle) result.textContent = `${cost[service]}${vehicle === 'european' ? ' · European/luxury parts and procedures can vary' : ''}`; };
  document.querySelectorAll('[data-cost-service],[data-cost-vehicle]').forEach(el => el.addEventListener('change', updateCost));
  document.querySelector('[data-make-lookup]')?.addEventListener('change', e => { const copy = { euro:'Start with the vehicle’s service schedule, correct fluid specifications and electronic diagnostic coverage.', specialty:'Specialty makes may have tighter procedures and model-specific parts; bring the symptom and service history.', all:'We service domestic and Asian makes too, with the same clear diagnosis and approval process.' }; document.querySelector('[data-make-result]').textContent = copy[e.target.value] || 'Make-specific notes appear here.'; });
  const seasonCopy = { heat:'Check battery condition, cooling-system behavior and air-conditioning performance before the heat exposes a weak point.', storm:'Check tires, wipers, lights, brakes and emergency supplies before storm conditions arrive.', rain:'Check tread depth, tire pressure, wipers and visibility. A small handling change is worth investigating.' };
  document.querySelectorAll('[data-season]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-season]').forEach(b => b.classList.remove('active')); button.classList.add('active'); document.querySelector('[data-season-result]').textContent = seasonCopy[button.dataset.season]; }));
  document.querySelector('[data-directions]')?.addEventListener('click', () => { const from = encodeURIComponent(document.querySelector('[data-address]').value || 'my location'); open(`https://www.google.com/maps/dir/${from}/770+N+State+Rd+7,+Plantation,+FL+33317`, '_blank', 'noopener'); });
  document.querySelectorAll('[data-service-filter]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-service-filter]').forEach(b => b.classList.remove('active')); button.classList.add('active'); const filter = button.dataset.serviceFilter; document.querySelectorAll('[data-service-filter-grid] [data-service-category]').forEach(card => { card.classList.toggle('hidden', filter !== 'all' && card.dataset.serviceCategory !== filter); card.classList.toggle('reflow-in', filter === 'all' || card.dataset.serviceCategory === filter); }); }));
  const quizText = { warning:'Start with Engine Diagnostics or Battery Testing, depending on the light and starting behavior.', wear:'Start with Tire Rotations or Wheel Alignments and let the wear pattern guide the next look.', move:'Start with Battery Testing for starting trouble or Transmission Repairs for shifting concerns.' };
  document.querySelectorAll('[data-quiz]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-quiz]').forEach(b => b.classList.remove('active')); button.classList.add('active'); const result = document.querySelector('[data-quiz-result]'); if (result) result.textContent = quizText[button.dataset.quiz]; }));
  document.querySelector('[data-mileage]')?.addEventListener('input', e => { const n = +e.target.value, result = document.querySelector('[data-mileage-result]'), marker = document.querySelector('[data-mileage-marker]'); const message = n >= 100000 ? 'At 100k+, ask for a full maintenance-history review and inspect age-related rubber, fluids and battery condition.' : n >= 60000 ? 'Around 60k, a broader fluid, brake, tire and suspension review is a useful conversation.' : n >= 30000 ? 'Around 30k, check the maintenance schedule, tire wear, brake condition and fluid intervals.' : 'Start with the owner’s schedule and keep oil, tire and brake observations current.'; if (result) result.textContent = message; if (marker) marker.style.left = `${Math.min(96, Math.max(4, n / 120000 * 100))}%`; });
  const warningCopy = { engine:'A check-engine light is a request for information. Note when it appears and avoid clearing it before diagnosis.', brake:'A brake warning or changed pedal feel deserves prompt attention. Call before continuing if stopping feels different.', battery:'A battery icon can point to charging-system behavior, not just battery age. Testing separates the possibilities.', tire:'A tire-pressure warning may be simple pressure loss or a puncture. Check pressure safely and inspect the tread.' };
  document.querySelectorAll('[data-warning]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-warning]').forEach(b => b.classList.remove('active')); button.classList.add('active'); const result = document.querySelector('[data-warning-result]'); if (result) result.textContent = warningCopy[button.dataset.warning]; }));
  document.querySelectorAll('.cert-card').forEach(card => card.addEventListener('mouseenter', () => card.classList.add('cert-open')));
  const compare = document.querySelector('[data-compare]'); if (compare) compare.addEventListener('input', e => e.target.closest('.compare-box').querySelector('.compare-after').style.width = `${e.target.value}%`);
  document.querySelectorAll('[data-coupon-filter]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-coupon-filter]').forEach(b => b.classList.remove('active')); button.classList.add('active'); const filter = button.dataset.couponFilter; document.querySelectorAll('.coupon-tool').forEach(card => card.classList.toggle('hidden', filter !== 'all' && card.dataset.couponCategory !== filter)); }));
  document.querySelectorAll('[data-copy]').forEach(button => button.addEventListener('click', async () => { try { await navigator.clipboard.writeText(button.dataset.copy); } catch {} button.textContent = 'Copied · call to confirm'; button.classList.add('copied'); setTimeout(() => { button.textContent = 'Copy call note'; button.classList.remove('copied'); }, 2200); }));
});
